'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from 'next/image'; // Import the Image component from 'next/image'
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showLogo, setShowLogo] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setShowLogo(false);
    }, 100); // 2 seconds

    return () => clearTimeout(timer);
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        {showLogo ? (

      <div className="flex justify-center items-center bg-black">
        <img src="/images/logo.png" className="w-[50%] h-[50%] bg-black rounded-full" alt="Logo" />
    </div>
        ) : (

          <div id="content-container" style={{ display: showLogo ? 'none' : 'block' }}>
          <Navbar />
        {children}
    </div>
        )}
    
      </body>
    </html>
  );
}
